### PR TITLE
Update Update libical, libgit2 and qtconnectivity

### PR DESCRIPTION
**Pull request by Sturmflut**
Fixed version of #125 and other previous pull requests created by flathubbot

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
@Sturmflut 

Thanks!

Do you happen to be interested in maintaining the package? Usually, the updates by flathubbot don't require intervention. But as you can see, from time to time something breaks.

**Comment by Alexander-Wilms** [comment]
Yes, the weekly releases are not trivial to handle.

I made an attempt that uses the Github API to query the libdc commit for a given Subsurface commit:

https://github.com/flathub/org.subsurface_divelog.Subsurface/pull/118/files

But maybe it's enough if Subsurface is cloned including the submodules


Another way would be to use Github Actions with a cron trigger:

https://github.com/flathub/com.github.theironrobin.siglo/blob/acc4267d42240bc7ee774144054f32fde6c2f964/.github/workflows/main.yml#L4

**Comment by Alexander-Wilms** [comment]
@Sturmflut Now the manifest is updated automatically and the libdc submodule is used. Once the bluez CUPS bug is fixed, the package shouldn't require manual intervention for a while. If you're interested, I can ask the Flathub admins to give you write access to the repo.

**Comment by Sturmflut** [comment]
@Alexander-Wilms That looks great! I can help maintain the package if I am assigned with the necessary rights, yes.

**Pull request merged**
